/**
 * backend-pipeline-generator.service.ts
 * Generates YAML (and Classic JSON for Node.js/Java) backend pipelines.
 */

import { Injectable, inject } from '@angular/core';
import { BackendGeneratorStateService } from './backend-generator-state.service';
import type {
  BackendLanguage,
  BackendDeployTargetType,
} from '../models/backend-generator.model';
import { BACKEND_ADO_GUIDS } from '../models/backend-generator.model';

export interface GeneratedBackendPipeline {
  fileName: string;
  content: string;
  type: 'yaml' | 'json';
}

@Injectable({ providedIn: 'root' })
export class BackendPipelineGeneratorService {
  private readonly state = inject(BackendGeneratorStateService);

  generate(): GeneratedBackendPipeline[] {
    const projectInfo = this.state.projectInfo();
    const langConfig = this.state.languageConfig();
    const buildConfig = this.state.buildConfig();
    const deployTarget = this.state.deployTarget();
    const environments = this.state.environments();
    const isAdo = projectInfo.ciPlatform === 'azure-devops';

    const files: GeneratedBackendPipeline[] = [];

    if (isAdo) {
      // ADO: generate build YAML
      files.push({
        fileName: `${projectInfo.projectName}-build.yml`,
        content: this.generateAdoBuildYaml(langConfig.language),
        type: 'yaml',
      });

      // ADO Classic JSON for Node.js and Java only (verified GUIDs)
      if (langConfig.language === 'nodejs' || langConfig.language === 'java') {
        files.push({
          fileName: `${projectInfo.projectName}-build-classic.json`,
          content: this.generateAdoBuildClassicJson(langConfig.language),
          type: 'json',
        });
      }

      // Release YAML for App Service
      if (deployTarget.type === 'app-service') {
        files.push({
          fileName: `${projectInfo.projectName}-release.yml`,
          content: this.generateAdoReleaseYaml(),
          type: 'yaml',
        });
      }
    } else {
      // GitHub Actions YAML
      files.push({
        fileName: `.github/workflows/${projectInfo.projectName}-ci.yml`,
        content: this.generateGitHubActionsYaml(langConfig.language),
        type: 'yaml',
      });
    }

    return files;
  }

  // ── ADO Build YAML ──────────────────────────────────────────────────────────

  private generateAdoBuildYaml(language: BackendLanguage): string {
    const info = this.state.projectInfo();
    const lang = this.state.languageConfig();
    const build = this.state.buildConfig();
    const envs = this.state.environments();

    const trigger = envs.scope === 'qa' ? envs.qaBranch
      : envs.scope === 'prod' ? envs.prodBranch
      : `${envs.qaBranch}\n  - ${envs.prodBranch}`;

    const steps = this.buildAdoYamlSteps(language);

    return `# Backend Build Pipeline — Generated by PipeForge
# Language: ${language} | Project: ${info.projectName}

trigger:
  branches:
    include:
      - ${trigger}

pool:
  vmImage: ubuntu-latest

steps:
${steps}

  - task: CopyFiles@2
    displayName: 'Copy artifacts'
    inputs:
      Contents: |
        **/*
        !node_modules/**
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '${info.projectName}-drop'
      publishLocation: 'Container'
`;
  }

  private buildAdoYamlSteps(language: BackendLanguage): string {
    const lang = this.state.languageConfig();
    const build = this.state.buildConfig();

    switch (language) {
      case 'nodejs':
        return this.nodejsYamlSteps(lang.nodeVersion, build);
      case 'java':
        return this.javaYamlSteps(lang.javaVersion, lang.javaBuildTool, build);
      case 'python':
        return this.pythonYamlSteps(lang.pythonVersion, build);
      case 'dotnet':
        return this.dotnetYamlSteps(lang.dotnetVersion, build);
      case 'go':
        return this.goYamlSteps(lang.goVersion, build);
      case 'php':
        return this.phpYamlSteps(lang.phpVersion, build);
      case 'ruby':
        return this.rubyYamlSteps(lang.rubyVersion, build);
      default:
        return '';
    }
  }

  private nodejsYamlSteps(version: string, build: { installCommand: string; runTests: boolean; testCommand: string; buildCommand: string; hasBuildStep: boolean }): string {
    const steps = [
      `  - task: NodeTool@0
    displayName: 'Use Node.js ${version}'
    inputs:
      versionSpec: '${version}'`,
      `  - task: Npm@1
    displayName: '${build.installCommand}'
    inputs:
      command: 'ci'`,
    ];
    if (build.runTests) {
      steps.push(`  - task: Npm@1
    displayName: 'Run tests'
    inputs:
      command: 'custom'
      customCommand: 'test'`);
    }
    if (build.hasBuildStep) {
      steps.push(`  - task: Npm@1
    displayName: 'Build'
    inputs:
      command: 'custom'
      customCommand: 'run build'`);
    }
    return steps.join('\n\n');
  }

  private javaYamlSteps(version: string, buildTool: string, build: { installCommand: string; runTests: boolean; testCommand: string; buildCommand: string; hasBuildStep: boolean }): string {
    const mvnGoal = build.runTests ? 'clean package' : 'clean package -DskipTests';
    if (buildTool === 'maven') {
      return `  - task: JavaToolInstaller@0
    displayName: 'Use Java ${version}'
    inputs:
      versionSpec: '${version}'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    displayName: 'Maven build'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: '${mvnGoal}'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.${version}'`;
    }
    return `  - task: JavaToolInstaller@0
    displayName: 'Use Java ${version}'
    inputs:
      versionSpec: '${version}'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - script: ./gradlew build${build.runTests ? '' : ' -x test'}
    displayName: 'Gradle build'`;
  }

  private pythonYamlSteps(version: string, build: { installCommand: string; runTests: boolean; testCommand: string; buildCommand: string; hasBuildStep: boolean }): string {
    const steps = [
      `  - task: UsePythonVersion@0
    displayName: 'Use Python ${version}'
    inputs:
      versionSpec: '${version}'`,
      `  - script: ${build.installCommand}
    displayName: 'Install dependencies'`,
    ];
    if (build.runTests) {
      steps.push(`  - script: ${build.testCommand}
    displayName: 'Run tests'`);
    }
    return steps.join('\n\n');
  }

  private dotnetYamlSteps(version: string, build: { installCommand: string; runTests: boolean; testCommand: string; buildCommand: string; hasBuildStep: boolean }): string {
    const steps = [
      `  - task: UseDotNet@2
    displayName: 'Use .NET ${version}'
    inputs:
      version: '${version}.x'`,
      `  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'`,
      `  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration Release'`,
    ];
    if (build.runTests) {
      steps.push(`  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      arguments: '--no-build --configuration Release'`);
    }
    steps.push(`  - task: DotNetCoreCLI@2
    displayName: 'Publish'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true`);
    return steps.join('\n\n');
  }

  private goYamlSteps(version: string, build: { installCommand: string; runTests: boolean; testCommand: string; buildCommand: string; hasBuildStep: boolean }): string {
    const steps = [
      `  - task: GoTool@0
    displayName: 'Use Go ${version}'
    inputs:
      version: '${version}'`,
      `  - script: go mod download
    displayName: 'Download modules'`,
    ];
    if (build.runTests) {
      steps.push(`  - script: go test ./...
    displayName: 'Run tests'`);
    }
    steps.push(`  - script: go build -o $(Build.ArtifactStagingDirectory)/app
    displayName: 'Build binary'`);
    return steps.join('\n\n');
  }

  private phpYamlSteps(version: string, build: { installCommand: string; runTests: boolean; testCommand: string; buildCommand: string; hasBuildStep: boolean }): string {
    const steps = [
      `  - task: UsePhpVersion@0
    displayName: 'Use PHP ${version}'
    inputs:
      version: '${version}'`,
      `  - script: ${build.installCommand}
    displayName: 'Install dependencies'`,
    ];
    if (build.runTests) {
      steps.push(`  - script: ${build.testCommand}
    displayName: 'Run tests'`);
    }
    return steps.join('\n\n');
  }

  private rubyYamlSteps(version: string, build: { installCommand: string; runTests: boolean; testCommand: string; buildCommand: string; hasBuildStep: boolean }): string {
    const steps = [
      `  - task: UseRubyVersion@0
    displayName: 'Use Ruby ${version}'
    inputs:
      versionSpec: '>= ${version}'`,
      `  - script: ${build.installCommand}
    displayName: 'Install gems'`,
    ];
    if (build.runTests) {
      steps.push(`  - script: ${build.testCommand}
    displayName: 'Run tests'`);
    }
    return steps.join('\n\n');
  }

  // ── ADO Build Classic JSON (Node.js + Java only) ────────────────────────────

  private generateAdoBuildClassicJson(language: BackendLanguage): string {
    const info = this.state.projectInfo();
    const lang = this.state.languageConfig();
    const build = this.state.buildConfig();

    const tasks = language === 'nodejs'
      ? this.nodejsClassicTasks(lang.nodeVersion, build)
      : this.javaClassicTasks(lang.javaVersion, lang.javaBuildTool, build);

    return JSON.stringify({
      name: `BUILD-${info.projectName}`,
      type: 2,
      quality: 1,
      path: '\\',
      project: { name: info.adoProject || info.projectName },
      variables: {},
      process: {
        phases: [
          {
            name: 'Agent job',
            refName: 'Job_1',
            condition: 'succeeded()',
            target: {
              executionOptions: { type: 0 },
              allowScriptsAuthAccessOption: false,
              type: 1,
            },
            steps: tasks,
          },
        ],
        type: 1,
        target: {
          agentSpecification: { identifier: 'ubuntu-latest' },
        },
      },
      repository: {
        id: '',
        type: 'GitHub',
        name: info.repositoryName,
        defaultBranch: 'refs/heads/main',
        clean: null,
        checkoutSubmodules: false,
      },
      triggers: [],
    }, null, 2);
  }

  private nodejsClassicTasks(version: string, build: { installCommand: string; runTests: boolean; testCommand: string; buildCommand: string; hasBuildStep: boolean }): unknown[] {
    const tasks: unknown[] = [
      {
        taskId: BACKEND_ADO_GUIDS.NodeTool,
        version: '0.*',
        name: `Use Node ${version}`,
        enabled: true,
        inputs: { versionSpec: version },
      },
      {
        taskId: BACKEND_ADO_GUIDS.Npm,
        version: '1.*',
        name: 'npm ci',
        enabled: true,
        inputs: { command: 'ci' },
      },
    ];
    if (build.runTests) {
      tasks.push({
        taskId: BACKEND_ADO_GUIDS.Npm,
        version: '1.*',
        name: 'npm test',
        enabled: true,
        inputs: { command: 'custom', customCommand: 'test' },
      });
    }
    if (build.hasBuildStep) {
      tasks.push({
        taskId: BACKEND_ADO_GUIDS.Npm,
        version: '1.*',
        name: 'npm run build',
        enabled: true,
        inputs: { command: 'custom', customCommand: 'run build' },
      });
    }
    tasks.push(
      {
        taskId: BACKEND_ADO_GUIDS.CopyFiles,
        version: '2.*',
        name: 'Copy artifacts',
        enabled: true,
        inputs: {
          Contents: '**/*\n!node_modules/**',
          TargetFolder: '$(Build.ArtifactStagingDirectory)',
        },
      },
      {
        taskId: BACKEND_ADO_GUIDS.PublishBuildArtifacts,
        version: '1.*',
        name: 'Publish artifact',
        enabled: true,
        inputs: {
          PathtoPublish: '$(Build.ArtifactStagingDirectory)',
          ArtifactName: 'drop',
          publishLocation: 'Container',
        },
      },
    );
    return tasks;
  }

  private javaClassicTasks(version: string, buildTool: string, build: { installCommand: string; runTests: boolean; testCommand: string; buildCommand: string; hasBuildStep: boolean }): unknown[] {
    const tasks: unknown[] = [
      {
        taskId: BACKEND_ADO_GUIDS.JavaToolInstaller,
        version: '0.*',
        name: `Use Java ${version}`,
        enabled: true,
        inputs: { versionSpec: version, jdkArchitectureOption: 'x64', jdkSourceOption: 'PreInstalled' },
      },
    ];
    if (buildTool === 'maven') {
      const goal = build.runTests ? 'clean package' : 'clean package -DskipTests';
      tasks.push({
        taskId: BACKEND_ADO_GUIDS.Maven,
        version: '3.*',
        name: 'Maven build',
        enabled: true,
        inputs: {
          mavenPomFile: 'pom.xml',
          goals: goal,
          javaHomeOption: 'JDKVersion',
          jdkVersionOption: `1.${version}`,
        },
      });
    }
    tasks.push(
      {
        taskId: BACKEND_ADO_GUIDS.CopyFiles,
        version: '2.*',
        name: 'Copy artifacts',
        enabled: true,
        inputs: {
          Contents: '**/*.jar\n**/*.war',
          TargetFolder: '$(Build.ArtifactStagingDirectory)',
        },
      },
      {
        taskId: BACKEND_ADO_GUIDS.PublishBuildArtifacts,
        version: '1.*',
        name: 'Publish artifact',
        enabled: true,
        inputs: {
          PathtoPublish: '$(Build.ArtifactStagingDirectory)',
          ArtifactName: 'drop',
          publishLocation: 'Container',
        },
      },
    );
    return tasks;
  }

  // ── ADO Release YAML (App Service) ──────────────────────────────────────────

  private generateAdoReleaseYaml(): string {
    const info = this.state.projectInfo();
    const deploy = this.state.deployTarget();
    const envs = this.state.environments();

    const appName = deploy.appService.appServiceName || `$(APP_SERVICE_NAME)`;

    return `# Backend Release Pipeline — Generated by PipeForge
# Deploys to Azure App Service

trigger: none

resources:
  pipelines:
    - pipeline: build
      source: 'BUILD-${info.projectName}'
      trigger: true

pool:
  vmImage: ubuntu-latest

stages:
${envs.scope !== 'prod' ? `  - stage: DeployQA
    displayName: 'Deploy to QA'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/${envs.qaBranch}')
    jobs:
      - deployment: DeployQA
        environment: QA
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy to App Service (QA)'
                  inputs:
                    azureSubscription: '${info.serviceConnectionId}'
                    appName: '${envs.qaAppServiceName || appName}-qa'
                    package: '$(Pipeline.Workspace)/build/**/*.zip'
` : ''}${envs.scope !== 'qa' ? `  - stage: DeployProd
    displayName: 'Deploy to Production'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/${envs.prodBranch}')
    jobs:
      - deployment: DeployProd
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy to App Service (Prod)'
                  inputs:
                    azureSubscription: '${info.serviceConnectionId}'
                    appName: '${envs.prodAppServiceName || appName}'
                    package: '$(Pipeline.Workspace)/build/**/*.zip'
` : ''}`;
  }

  // ── GitHub Actions YAML ─────────────────────────────────────────────────────

  private generateGitHubActionsYaml(language: BackendLanguage): string {
    const info = this.state.projectInfo();
    const lang = this.state.languageConfig();
    const build = this.state.buildConfig();
    const envs = this.state.environments();

    const steps = this.buildGitHubActionsSteps(language);

    return `# GitHub Actions CI/CD — Generated by PipeForge
# Language: ${language} | Project: ${info.projectName}

name: CI/CD

on:
  push:
    branches: [${envs.qaBranch}, ${envs.prodBranch}]
  pull_request:
    branches: [${envs.prodBranch}]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

${steps}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${info.projectName}-drop
          path: dist/
          retention-days: 5
`;
  }

  private buildGitHubActionsSteps(language: BackendLanguage): string {
    const lang = this.state.languageConfig();
    const build = this.state.buildConfig();

    switch (language) {
      case 'nodejs':
        return `      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${lang.nodeVersion}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
${build.runTests ? `
      - name: Run tests
        run: npm test` : ''}
${build.hasBuildStep ? `
      - name: Build
        run: npm run build` : ''}`;

      case 'java':
        return `      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '${lang.javaVersion}'
          distribution: 'temurin'

      - name: Build with ${lang.javaBuildTool === 'maven' ? 'Maven' : 'Gradle'}
        run: ${lang.javaBuildTool === 'maven' ? `mvn clean package${build.runTests ? '' : ' -DskipTests'}` : `./gradlew build${build.runTests ? '' : ' -x test'}`}`;

      case 'python':
        return `      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '${lang.pythonVersion}'

      - name: Install dependencies
        run: ${build.installCommand}
${build.runTests ? `
      - name: Run tests
        run: ${build.testCommand}` : ''}`;

      case 'dotnet':
        return `      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '${lang.dotnetVersion}.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release
${build.runTests ? `
      - name: Test
        run: dotnet test --no-build --configuration Release` : ''}

      - name: Publish
        run: dotnet publish --configuration Release --output ./dist`;

      case 'go':
        return `      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '${lang.goVersion}'

      - name: Download modules
        run: go mod download
${build.runTests ? `
      - name: Test
        run: go test ./...` : ''}

      - name: Build
        run: go build -o dist/app`;

      case 'php':
        return `      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${lang.phpVersion}'

      - name: Install dependencies
        run: ${build.installCommand}
${build.runTests ? `
      - name: Test
        run: ${build.testCommand}` : ''}`;

      case 'ruby':
        return `      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${lang.rubyVersion}'
          bundler-cache: true
${build.runTests ? `
      - name: Run tests
        run: ${build.testCommand}` : ''}`;

      default:
        return '';
    }
  }

  // ── Download helper ─────────────────────────────────────────────────────────

  downloadAll(): void {
    const files = this.generate();
    files.forEach(f => {
      const blob = new Blob([f.content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = f.fileName.includes('/') ? f.fileName.split('/').pop()! : f.fileName;
      a.click();
      URL.revokeObjectURL(url);
    });
  }
}
