import { Injectable, inject } from '@angular/core';
import { MobileGeneratorStateService } from './mobile-generator-state.service';
import type { MobileFramework, MobileTargetPlatform } from '../models/mobile-generator.model';

export interface GeneratedMobilePipeline {
  fileName: string;
  content: string;
  platform: string;
}

@Injectable({ providedIn: 'root' })
export class MobilePipelineGeneratorService {
  private readonly state = inject(MobileGeneratorStateService);

  generate(): GeneratedMobilePipeline[] {
    const { framework, targetPlatform } = {
      framework: this.state.frameworkConfig().framework,
      targetPlatform: this.state.platformConfig().targetPlatform,
    };
    const isAdo = this.state.projectInfo().ciPlatform === 'azure-devops';
    const files: GeneratedMobilePipeline[] = [];

    if (targetPlatform === 'android' || targetPlatform === 'both') {
      files.push({
        fileName: isAdo
          ? `${this.state.projectInfo().projectName}-android.yml`
          : `.github/workflows/${this.state.projectInfo().projectName}-android.yml`,
        content: this.generateAndroidPipeline(framework, isAdo),
        platform: 'Android',
      });
    }

    if (targetPlatform === 'ios' || targetPlatform === 'both') {
      files.push({
        fileName: isAdo
          ? `${this.state.projectInfo().projectName}-ios.yml`
          : `.github/workflows/${this.state.projectInfo().projectName}-ios.yml`,
        content: this.generateIosPipeline(framework, isAdo),
        platform: 'iOS',
      });
    }

    return files;
  }

  private generateAndroidPipeline(framework: MobileFramework, isAdo: boolean): string {
    const info = this.state.projectInfo();
    const fw = this.state.frameworkConfig();
    const build = this.state.buildConfig();
    const dist = this.state.distributionConfig();
    const platform = this.state.platformConfig();

    const isRelease = build.buildType === 'release';
    const hasDistribution = dist.distribution !== 'none';
    const useAppCenter = dist.distribution === 'app-center';

    if (isAdo) {
      return `# Android Pipeline — Generated by PipeForge
# Framework: ${framework} | Project: ${info.projectName}

trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: ubuntu-latest

steps:
${this.androidAdoSteps(framework, fw.nodeVersion, fw.flutterVersion, isRelease, useAppCenter, dist.appCenterAndroidApp, dist.appCenterDistributionGroup)}`;
    }

    return `# Android GitHub Actions — Generated by PipeForge
# Framework: ${framework} | Project: ${info.projectName}

name: Android CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

${this.androidGhaSteps(framework, fw.nodeVersion, fw.flutterVersion, isRelease, useAppCenter, dist.appCenterAndroidApp, dist.appCenterDistributionGroup)}`;
  }

  private androidAdoSteps(framework: MobileFramework, nodeVersion: string, flutterVersion: string, isRelease: boolean, useAppCenter: boolean, appName: string, distGroup: string): string {
    const buildVariant = isRelease ? 'Release' : 'Debug';
    const gradleTask = isRelease ? 'assembleRelease' : 'assembleDebug';

    switch (framework) {
      case 'react-native':
        return `  - task: NodeTool@0
    displayName: 'Use Node.js ${nodeVersion}'
    inputs:
      versionSpec: '${nodeVersion}'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'

  - task: Gradle@0
    displayName: 'Build Android (${buildVariant})'
    inputs:
      gradleWrapperFile: 'android/gradlew'
      workingDirectory: 'android'
      tasks: '${gradleTask}'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
${useAppCenter ? `
  - task: AppCenterDistribute@3
    displayName: 'Distribute to App Center'
    inputs:
      serverEndpoint: 'App Center'
      appSlug: '${appName || 'org/android-app'}'
      appFile: 'android/app/build/outputs/apk/${isRelease ? 'release' : 'debug'}/*.apk'
      distributionGroupId: '${distGroup}'` : ''}`;

      case 'flutter':
        return `  - task: FlutterInstall@0
    displayName: 'Install Flutter ${flutterVersion}'
    inputs:
      mode: 'auto'
      version: 'specific'
      versionSpec: '${flutterVersion}'

  - script: flutter pub get
    displayName: 'Get packages'

  - script: flutter test
    displayName: 'Run tests'

  - script: flutter build apk --${isRelease ? 'release' : 'debug'}
    displayName: 'Build APK (${buildVariant})'
${useAppCenter ? `
  - task: AppCenterDistribute@3
    displayName: 'Distribute to App Center'
    inputs:
      serverEndpoint: 'App Center'
      appSlug: '${appName || 'org/android-app'}'
      appFile: 'build/app/outputs/flutter-apk/app-${isRelease ? 'release' : 'debug'}.apk'
      distributionGroupId: '${distGroup}'` : ''}`;

      case 'android-native':
        return `  - task: Gradle@0
    displayName: 'Build Android (${buildVariant})'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: '${gradleTask}'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
${useAppCenter ? `
  - task: AppCenterDistribute@3
    displayName: 'Distribute to App Center'
    inputs:
      serverEndpoint: 'App Center'
      appSlug: '${appName || 'org/android-app'}'
      appFile: 'app/build/outputs/apk/${isRelease ? 'release' : 'debug'}/*.apk'
      distributionGroupId: '${distGroup}'` : ''}`;

      default:
        return '  # No Android steps for this framework';
    }
  }

  private androidGhaSteps(framework: MobileFramework, nodeVersion: string, flutterVersion: string, isRelease: boolean, useAppCenter: boolean, appName: string, distGroup: string): string {
    const buildVariant = isRelease ? 'release' : 'debug';

    switch (framework) {
      case 'react-native':
        return `      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'

      - name: Install dependencies
        run: npm install

      - name: Build Android
        run: cd android && ./gradlew assemble${isRelease ? 'Release' : 'Debug'}
${useAppCenter ? `
      - name: Distribute to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${appName || 'org/android-app'}
          token: \${{ secrets.APP_CENTER_TOKEN }}
          group: ${distGroup}
          file: android/app/build/outputs/apk/${buildVariant}/app-${buildVariant}.apk` : ''}`;

      case 'flutter':
        return `      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '${flutterVersion}'

      - name: Get packages
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --${buildVariant}`;

      default:
        return `      - name: Build Android
        run: ./gradlew assemble${isRelease ? 'Release' : 'Debug'}`;
    }
  }

  private generateIosPipeline(framework: MobileFramework, isAdo: boolean): string {
    const info = this.state.projectInfo();
    const fw = this.state.frameworkConfig();
    const build = this.state.buildConfig();
    const dist = this.state.distributionConfig();

    const isRelease = build.buildType === 'release';
    const useAppCenter = dist.distribution === 'app-center';
    const useTestFlight = dist.distribution === 'testflight';

    if (isAdo) {
      return `# iOS Pipeline — Generated by PipeForge
# Framework: ${framework} | Project: ${info.projectName}

trigger:
  branches:
    include:
      - main

pool:
  vmImage: macOS-latest

steps:
${this.iosAdoSteps(framework, fw.nodeVersion, fw.flutterVersion, isRelease, useAppCenter, useTestFlight, dist.appCenterIosApp, dist.appCenterDistributionGroup)}`;
    }

    return `# iOS GitHub Actions — Generated by PipeForge
# Framework: ${framework} | Project: ${info.projectName}

name: iOS CI

on:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

${this.iosGhaSteps(framework, fw.nodeVersion, fw.flutterVersion, isRelease)}`;
  }

  private iosAdoSteps(framework: MobileFramework, nodeVersion: string, flutterVersion: string, isRelease: boolean, useAppCenter: boolean, useTestFlight: boolean, appName: string, distGroup: string): string {
    const configuration = isRelease ? 'Release' : 'Debug';

    switch (framework) {
      case 'react-native':
        return `  - task: NodeTool@0
    displayName: 'Use Node.js ${nodeVersion}'
    inputs:
      versionSpec: '${nodeVersion}'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'

  - task: CocoaPods@0
    displayName: 'CocoaPods install'
    inputs:
      workingDirectory: 'ios'

  - task: Xcode@5
    displayName: 'Build iOS (${configuration})'
    inputs:
      actions: 'build'
      configuration: '${configuration}'
      sdk: 'iphoneos'
      xcWorkspacePath: 'ios/*.xcworkspace'
      scheme: '$(SCHEME_NAME)'
${useAppCenter ? `
  - task: AppCenterDistribute@3
    displayName: 'Distribute to App Center'
    inputs:
      serverEndpoint: 'App Center'
      appSlug: '${appName || 'org/ios-app'}'
      appFile: '$(Build.ArtifactStagingDirectory)/*.ipa'
      distributionGroupId: '${distGroup}'` : ''}`;

      case 'flutter':
        return `  - task: FlutterInstall@0
    displayName: 'Install Flutter ${flutterVersion}'
    inputs:
      mode: 'auto'
      version: 'specific'
      versionSpec: '${flutterVersion}'

  - script: flutter pub get
    displayName: 'Get packages'

  - script: flutter build ios --${isRelease ? 'release' : 'debug'} --no-codesign
    displayName: 'Build iOS (${configuration})'

  - task: Xcode@5
    displayName: 'Archive iOS app'
    inputs:
      actions: 'archive'
      configuration: '${configuration}'
      xcWorkspacePath: 'ios/*.xcworkspace'
      scheme: 'Runner'`;

      case 'ios-native':
        return `  - task: Xcode@5
    displayName: 'Build iOS (${configuration})'
    inputs:
      actions: 'build'
      configuration: '${configuration}'
      sdk: 'iphoneos'
      xcWorkspacePath: '*.xcworkspace'
      scheme: '$(SCHEME_NAME)'
      signingOption: 'default'
      xcodeVersion: 'default'`;

      default:
        return '  # No iOS steps for this framework';
    }
  }

  private iosGhaSteps(framework: MobileFramework, nodeVersion: string, flutterVersion: string, isRelease: boolean): string {
    const configuration = isRelease ? 'Release' : 'Debug';

    switch (framework) {
      case 'react-native':
        return `      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: cd ios && pod install

      - name: Build iOS
        run: xcodebuild -workspace ios/*.xcworkspace -scheme "$(SCHEME_NAME)" -configuration ${configuration} -sdk iphoneos build`;

      case 'flutter':
        return `      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '${flutterVersion}'

      - name: Get packages
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --${isRelease ? 'release' : 'debug'} --no-codesign`;

      case 'ios-native':
        return `      - name: Build iOS
        run: xcodebuild -workspace *.xcworkspace -scheme "$(SCHEME_NAME)" -configuration ${configuration} -sdk iphoneos build`;

      default:
        return `      - name: Build iOS
        run: xcodebuild build`;
    }
  }

  downloadAll(): void {
    const files = this.generate();
    files.forEach(f => {
      const blob = new Blob([f.content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = f.fileName.includes('/') ? f.fileName.split('/').pop()! : f.fileName;
      a.click();
      URL.revokeObjectURL(url);
    });
  }
}
